pipeline {
    agent any
    environment {
        TEST_ENV_VAR = 'test environment variable'
    }
    stages {
        stage('Pre-Build') {
            steps {
               // any pre-build steps
               echo "Environment variable is: ${TEST_ENV_VAR}"
            }
            
        }
    }
}
